### ISSUE TITLE
High bit depth support

### ISSUE THREAD

**Issue by TbtBI** [crabshank/Avisynth-filters#2]
Can you add high bit depth support?

Thanks.

**Comment by crabshank** [comment]
I may add Rec. 2020 support when I next devote time to updating these filters, but at the moment it's not a high priority.

Apologies.

**Comment by TbtBI** [comment]
When you have the time.
Thanks.

Update: 
```
8-bit yuv input
a=converttorgb24(matrix="rec709").whitepoint().converttoplanarrgb()
b=converttoplanarrgb(matrix="rec709").whitepoint()
Compare(a,b,"rgb")
```

Shouldn't both a and b have identical output?

```
8-bit yuv input
ConvertBits(16)
converttoplanarrgb(matrix="rec709")
whitepoint()
```

That one has wrong output. Omitting ConvertBits(16) the output looks fine. Also replacing ConvertBits(16) and  converttoplanarrgb(matrix="rec709") with converttorgb48(matrix="rec709") the output is fine.

**Comment by crabshank** [comment]
Should only accept RGB32.

**Comment by crabshank** [comment]
> Can you add high bit depth support?
> 
> Thanks.

Finally added Rec. 2020 and RGB64 support to Manual_WP and Auto_Gamma. I can't be 100% sure that the RGB64 output is correct because my output is 0-255, but if it turns out to be wrong I'll try a fix.

**Comment by TbtBI** [comment]
It works fine.
Thanks.
